// Two-language text for strings that live in scripts. The page language comes from <html lang>:
// index.html is Turkish, en.html (generated by _dev/build-en.ps1) is English.

export const LANG = document.documentElement.lang === 'en' ? 'en' : 'tr';
export const LOCALE = LANG === 'en' ? 'en-GB' : 'tr-TR';

/** t('Türkçe metin', 'English text') → the one for the current page. */
export const t = (tr, en) => (LANG === 'en' ? en : tr);

/** The eight lifecycle stages, in order (rail, 3D loop ring). */
export const STAGE_NAMES = Object.freeze(t(
  ['Tasarım', 'Üretim', 'Depolama', 'Nakliye', 'Kurulum', 'Söküm', 'Bakım', 'Yeniden Kullanım'],
  ['Design', 'Production', 'Storage', 'Transport', 'Installation', 'Dismantling', 'Maintenance', 'Reuse'],
));
