# Builds every page of the site, in Turkish and in English, and sitemap.xml.
#   _dev/site.html     the source: all sections in one file ("@only" blocks say which pages a part belongs to,
#                      "{{...}}" marks are filled in per page)
#   _dev/pages.json    the pages: file names, sections, titles and descriptions
#   _dev/i18n/en.json  Turkish -> English text pairs
# Edit those files and run this script again; never edit the generated pages by hand.
# Lives in _dev/, which the web server does not serve; the site is the folder above it.
# This file is ASCII on purpose: Windows PowerShell 5.1 misreads UTF-8 scripts without a BOM.
$root = Split-Path $PSScriptRoot -Parent
$base = 'https://nilus.com.tr/'
$utf8 = New-Object System.Text.UTF8Encoding $false
$site = [IO.File]::ReadAllText("$PSScriptRoot\site.html", $utf8)
$conf = ConvertFrom-Json ([IO.File]::ReadAllText("$PSScriptRoot\pages.json", $utf8))
$pairs = ConvertFrom-Json ([IO.File]::ReadAllText("$PSScriptRoot\i18n\en.json", $utf8))
# Longest first, so a whole sentence is translated before any word inside it can match on its own.
$pairs = $pairs | Sort-Object { $_[0].Length } -Descending
$pages = @($conf.pages)
$nl = if ($site.Contains("`r`n")) { "`r`n" } else { "`n" }

# The page a section lives on.
$owner = @{}
foreach ($p in $pages) { foreach ($s in $p.sections) { $owner[$s] = $p } }

# A page's address as written in links; the Turkish home page is the folder itself.
function PageHref($page, $lang) {
  $file = if ($lang -eq 'en') { $page.en } else { $page.tr }
  if ($file -eq 'index.html') { './' } else { $file }
}
function PageUrl($page, $lang) {
  $href = PageHref $page $lang
  if ($href -eq './') { $base } else { $base + $href }
}
# A link to a section on another page. The page's opening section needs no anchor.
function SectionHref($id, $lang) {
  $page = $owner[$id]
  $href = PageHref $page $lang
  if ($id -eq $page.sections[0] -or $id -eq 'process') { $href } else { "$href#$id" }
}
function Field($page, $name, $lang, $fallback) {
  $key = if ($lang -eq 'en') { $name + 'En' } else { $name }
  $value = $page.$key
  if ($value) { $value } else { $fallback }
}

function NavHtml($page, $lang) {
  $lines = @()
  foreach ($p in $pages) {
    $here = $p.id -eq $page.id
    # On the home page "Surec" scrolls down to the process itself (the hero sits above it).
    $href = if ($here -and $p.sections -contains 'process') { '#process' } else { PageHref $p $lang }
    $current = if ($here) { ' aria-current="page"' } else { '' }
    $lines += "          <li><a href=`"$href`"$current>$($p.name)</a></li>"
  }
  if ($lang -eq 'en') {
    $lines += "          <li><a class=`"nav-lang`" href=`"$(PageHref $page 'tr')`" lang=`"tr`" hreflang=`"tr`" aria-label=`"$($conf.labels.turkish)`">TR</a></li>"
  } else {
    $lines += "          <li><a class=`"nav-lang`" href=`"$(PageHref $page 'en')`" lang=`"en`" hreflang=`"en`" aria-label=`"English`">EN</a></li>"
  }
  $lines -join $nl
}

# The end of every page: on to the next page, and buttons for the others.
function NextHtml($page, $lang) {
  $i = [Array]::IndexOf($pages, $page)
  $next = $pages[($i + 1) % $pages.Count]
  $lines = @(
    "    <section class=`"section page-next`" aria-label=`"$($conf.labels.others)`">",
    "      <div class=`"wrap page-next-inner`">",
    "        <a class=`"page-next-main`" href=`"$(PageHref $next $lang)`" data-reveal>",
    "          <span class=`"page-next-label`">$($conf.labels.next)</span>",
    "          <span class=`"page-next-name`"><span>$($next.name)</span><span class=`"page-next-arrow`" aria-hidden=`"true`">&rarr;</span></span>",
    "        </a>",
    "        <ul class=`"page-next-others`" data-reveal>"
  )
  foreach ($p in $pages) {
    if ($p.id -eq $page.id -or $p.id -eq $next.id) { continue }
    $lines += "          <li><a class=`"btn btn-ghost btn-small`" href=`"$(PageHref $p $lang)`">$($p.name)</a></li>"
  }
  $lines += "        </ul>", "      </div>", "    </section>"
  $lines -join $nl
}

# Old links into the single page (nilus.com.tr/#iletisim): where each section lives now.
function MovedJson($page, $lang) {
  $items = @()
  foreach ($id in $owner.Keys | Sort-Object) {
    if ($owner[$id].id -ne $page.id) { $items += "`"#$id`": `"$(SectionHref $id $lang)`"" }
  }
  '{ ' + ($items -join ', ') + ' }'
}

function BuildPage($page, $lang) {
  $html = $site
  # Parts that belong to other pages go.
  $html = [regex]::Replace($html, '(?s)[ \t]*<!-- @only ([a-z ]+) -->\r?\n(.*?)[ \t]*<!-- @end -->\r?\n', {
    param($m)
    if (($m.Groups[1].Value -split ' ') -contains $page.id) { $m.Groups[2].Value } else { '' }
  })
  $html = [regex]::Replace($html, '<!-- SOURCE of every page[^\r\n]*-->', '<!-- Generated by _dev/build.ps1 from _dev/site.html. Edit the source, then rebuild. -->')

  $title = Field $page 'title' $lang ''
  $description = Field $page 'description' $lang ''
  $fill = [ordered]@{
    '{{title}}' = $title
    '{{description}}' = $description
    '{{og-title}}' = Field $page 'ogTitle' $lang $title
    '{{og-description}}' = Field $page 'ogDescription' $lang $description
    '{{url}}' = PageUrl $page $lang
    '{{url-tr}}' = PageUrl $page 'tr'
    '{{url-en}}' = PageUrl $page 'en'
    '{{home}}' = if ($page.sections -contains 'hero') { '#hero' } else { PageHref $pages[0] $lang }
    '{{nav}}' = NavHtml $page $lang
    '{{page-next}}' = NextHtml $page $lang
    '{{moved}}' = MovedJson $page $lang
  }
  foreach ($key in $fill.Keys) { $html = $html.Replace($key, [string]$fill[$key]) }

  # In-page links to sections that now live on another page.
  $html = [regex]::Replace($html, 'href="#([A-Za-z0-9_-]+)"', {
    param($m)
    $id = $m.Groups[1].Value
    if ($owner.ContainsKey($id) -and $owner[$id].id -ne $page.id) { 'href="' + (SectionHref $id $lang) + '"' } else { $m.Value }
  })

  # A page without the hero opens with its section's title: that is the page's main heading.
  if (-not ($page.sections -contains 'hero')) {
    $html = ([regex]'<h2 ').Replace($html, '<h1 ', 1, $html.IndexOf('<main'))
    $html = ([regex]'</h2>').Replace($html, '</h1>', 1, $html.IndexOf('<main'))
  }
  $html
}

# Anything still carrying Turkish letters was not translated (the language link is expected).
$turkish = '[çğıöşüÇĞİÖŞÜâ]'
$used = @{}
$left = @()
$open = @()
foreach ($page in $pages) {
  $html = BuildPage $page 'tr'
  [IO.File]::WriteAllText("$root\$($page.tr)", $html, $utf8)
  if ($html -match '\{\{|@only|@end') { $open += $page.tr }

  $html = BuildPage $page 'en'
  foreach ($pair in $pairs) {
    if ($html.IndexOf($pair[0], [StringComparison]::Ordinal) -lt 0) { continue }
    $used[$pair[0]] = $true
    $html = $html.Replace($pair[0], $pair[1])
  }
  [IO.File]::WriteAllText("$root\$($page.en)", $html, $utf8)
  if ($html -match '\{\{|@only|@end') { $open += $page.en }
  $n = 0
  foreach ($line in ($html -split "`n")) {
    $n++
    # Brand names and the postal address keep their own spelling (matched loosely here so this file stays ASCII).
    $probe = $line -replace 'Pa.abah.e|Ar.elik|Eczac.ba..|Ata.ehir|.stanbul', ''
    if ($probe -cmatch $turkish -and $line -notmatch 'class="nav-lang"') { $left += ("{0}:{1}: {2}" -f $page.en, $n, $line.Trim()) }
  }
  "{0,-20} {1,-20} {2,7:N0} characters" -f $page.tr, $page.en, $html.Length
}

# sitemap.xml: every page, each with its other-language twin.
$map = @('<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">')
foreach ($page in $pages) {
  foreach ($lang in 'tr', 'en') {
    $map += '  <url>'
    $map += "    <loc>$(PageUrl $page $lang)</loc>"
    $map += "    <xhtml:link rel=`"alternate`" hreflang=`"tr`" href=`"$(PageUrl $page 'tr')`"/>"
    $map += "    <xhtml:link rel=`"alternate`" hreflang=`"en`" href=`"$(PageUrl $page 'en')`"/>"
    $map += '  </url>'
  }
}
$map += '</urlset>'
[IO.File]::WriteAllText("$root\sitemap.xml", ($map -join "`n") + "`n", $utf8)

$missing = @($pairs | Where-Object { -not $used.ContainsKey($_[0]) } | ForEach-Object { $_[0] })
"pairs not found on any page: $($missing.Count)"; $missing | ForEach-Object { "  - $_" }
"lines still in Turkish: $($left.Count)"; $left | ForEach-Object { "  $_" }
"unfilled marks: $($open.Count)"; $open | ForEach-Object { "  $_" }
